services:
  comfyui:
    build: .
    image: isekai:local
    ports:
      - "127.0.0.1:8188:8188"
    volumes:
      - ./models:/opt/ComfyUI/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
