#!/usr/bin/env python3
"""PROTOTYPE — N21: flow `A` at its best, on photographs of a real person.

Every render in round 2 has been of a **synthetic** subject: generated by an SDXL
model, evenly lit, frontal, one face, no lens. The product's actual input is a
phone photograph. This is the first time the settled flow meets one.

Flow `A` exactly as F34 and F35 left it -- `cn_strength 0.8`, `cfg 5`, WAI's
quality string leading the prompt, and the hires pass at the recommendation's
upper denoise, which is the value that measured best for `A`.

**Three photographs, three sheets, one person.** The hair colour differs between
them, which no synthetic subject posed: `real_photo_3` is blonde and the other two are
brown, months apart. Each sheet describes **its own photograph** rather than the
person -- which is what `notes/CRITERIA.md` §1 means by the sheet being the
ground truth,
and the reason a per-photo sheet is the right unit.

**Tattoos are declared and expected to fail as design.** F23 found no
general-purpose stylizer carries specific ink through a strong style change, and
the operator has set them aside for now. `tattoo` is in the sheets so their
*presence* can be judged; nobody should read the motifs.

**Renders are gitignored, as are the sheets and the photographs** (design.md D14).

    PYTHONPATH=. uv run python prototype/real_photo.py --server http://127.0.0.1:8188
"""

import argparse
import json
from pathlib import Path

from isekai.comfy_client import ComfyClient
from isekai.pipeline import _render
from isekai.workflow import image_dimensions, inject, working_resolution
from prototype.combined import CFG, CN_STRENGTH
from prototype.face_ladder import INSTANTID, SAMPLER
from prototype.fromnoise import (
    GRAPH,
    LATENT,
    NEGATIVE,
    POSITIVE,
    SEED,
    check_graph,
    prompts_of,
)
from prototype.hires import RESIZE, add_hires, check_hires
from prototype.ladder_position import build
from prototype.paths import render_dir, sheet_path

PHOTOS = Path("prototype/inputs/real")

# sheet id -> the photograph it was written from. Held here rather than in the
# sheet because every other runner derives the path from the id, and these
# filenames are camera-assigned and cannot be derived from anything.
SUBJECTS = {
    "real_photo_1": "real_photo_original.jpeg",
    "real_photo_3": "photo_2569-09-07 21.09.10.jpeg",
}
# `real_photo_2` was withdrawn by the operator on 2026-09-10. Its **renders and
# its sheet stay on disk** -- F36 was measured on all three and deleting the
# subject would make that finding unreproducible -- but it is out of SUBJECTS, so
# nothing tries to read a photograph that is gone. The id is **not reused**: a
# later subject numbered 2 would silently inherit its renders.
HIRES_DENOISE = 0.50  # F35: the value that measured best for flow A

# Both kept flows, with and without the second pass. `D` drops InstantID and
# OpenPose, so it never reads the photograph -- which on a real subject is the
# starker comparison: `A` has a face embedding to work from and `D` has only the
# sheet a human wrote.
ARMS = {
    "1_flow_a": "A",
    "2_flow_a_hires": "A",
    "3_flow_d": "D",
    "4_flow_d_hires": "D",
}


def main() -> None:
    """Render flow A, with and without the hires pass, on each photograph."""
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--server", default="http://127.0.0.1:8188")
    p.add_argument("--out", type=Path, default=render_dir("n21_real_photo"))
    p.add_argument("--subjects", nargs="*", default=list(SUBJECTS))
    p.add_argument("--only", default=None)
    p.add_argument("--pod-image", default=None)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    base = json.loads(GRAPH.read_text())
    check_graph(base)
    client = None if args.dry_run else ComfyClient(args.server)

    for sid in args.subjects:
        photo = PHOTOS / SUBJECTS[sid]
        if not photo.exists():
            raise SystemExit(f"{photo} is missing")
        prompt, negative = prompts_of(sheet_path(sid))
        width, height = working_resolution(*image_dimensions(str(photo)))

        for arm, flow in ARMS.items():
            if args.only and arm != args.only:
                continue
            dest = args.out / arm / sid
            if (dest / "0.png").exists():
                print(f"skip {dest}")
                continue

            g = build(base, flow)
            g[POSITIVE]["inputs"]["text"] = prompt
            g[NEGATIVE]["inputs"]["text"] = negative
            g[LATENT]["inputs"].update(width=width, height=height)
            if INSTANTID in g:
                g[INSTANTID]["inputs"]["cn_strength"] = CN_STRENGTH
            g[SAMPLER]["inputs"].update(cfg=CFG, seed=SEED)

            print(f"\n=== {arm} / {sid} ===  flow {flow} · {width}x{height}")
            if client is None:
                continue
            # Injected before the hires stage exists, because `inject` resolves
            # `find_node(class_type="ImageScale")` and the hires resize is a
            # second one -- see `hires.py`.
            inject(g, client.upload_image(str(photo)), str(photo))
            if arm.endswith("hires"):
                add_hires(g, width, height, HIRES_DENOISE)
                check_hires(g)
                t = g[RESIZE]["inputs"]
                print(
                    f"    hires -> {t['width']}x{t['height']} "
                    f"at denoise {HIRES_DENOISE}"
                )

            dest.mkdir(parents=True, exist_ok=True)
            _render(client, g, dest / "0.png")
            (dest / "arm.json").write_text(
                json.dumps(
                    {
                        "arm": arm,
                        "subject": sid,
                        "photo": str(photo),
                        "seed": SEED,
                        "cn_strength": CN_STRENGTH,
                        "cfg": CFG,
                        "hires_denoise": HIRES_DENOISE
                        if arm.endswith("hires")
                        else None,
                        "pod_image": args.pod_image,
                    },
                    indent=2,
                )
                + "\n"
            )


if __name__ == "__main__":
    main()
